[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
admin_passwd = admin

db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
db_name = odoo18

; Active le mode développeur automatiquement
dev_mode = reload

; Logs lisibles
log_level = info
log_handler = :INFO

; Performance (dev)
workers = 0
max_cron_threads = 1
